master:
  build: .
  container_name: master
  command:
    - roscore

talker:
  build: .
  container_name: talker
  environment:
#    - "ROS_HOSTNAME=172.17.0.4"
#    - "ROS_MASTER_URI=http://172.17.0.2:11311"
    - "ROS_HOSTNAME=talker"
    - "ROS_MASTER_URI=http://master:11311"
  command: rosrun roscpp_tutorials talker

listener:
  build: .
  container_name: listener
  environment:
#    - "ROS_HOSTNAME=172.17.0.3"
#    - "ROS_MASTER_URI=http://172.17.0.2:11311"
    - "ROS_HOSTNAME=listener"
    - "ROS_MASTER_URI=http://master:11311"
  command: rosrun roscpp_tutorials listener
